# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run:
          name: Setup the OS
          command: |
            sudo dpkg --add-architecture armhf
            echo "foreign-architecture armhf" >> /etc/dpkg/dpkg.cfg.d/architectures
            apt-get update
            sudo apt-get -y install libstdc++:armhf 

      - run:
          name: info
          command: |
            sudo apt-get -y install facter
            sudo facter





workflows:
  build:
    jobs:
      - build-medium

