# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: dpkg --version
      - run: dpkg --print-architecture
      - run: dpkg --print-foreign-architectures
      - run: whoami
      - run: sudo dpkg --add-architecture armhf
      - run: echo "Hello, Arm!"

workflows:
  build:
    jobs:
      - build-medium

